# Generated by Django 2.0.4 on 2018-04-30 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_plan',
            new_name='image',
        ),
    ]
