# Generated by Django 2.0.4 on 2018-06-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamificationAdvice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('advice', models.CharField(default='', max_length=254)),
            ],
        ),
        migrations.AlterModelOptions(
            name='commitskill',
            options={'verbose_name': 'Skill Coverage', 'verbose_name_plural': 'Skills Coverage'},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'verbose_name': 'Bugs & Issues', 'verbose_name_plural': 'Bugs & Issues'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project Summary', 'verbose_name_plural': 'Projects Summary'},
        ),
        migrations.AlterModelOptions(
            name='projectstate',
            options={'verbose_name': 'Project State', 'verbose_name_plural': 'Projects States'},
        ),
        migrations.AlterModelOptions(
            name='requiredskills',
            options={'verbose_name': 'Required Skillset', 'verbose_name_plural': 'Required Skillsets'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
    ]
