# Generated by Django 2.0.4 on 2018-05-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180430_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='issues',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='proposed', max_length=254),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
    ]
