# Generated by Django 2.0.4 on 2018-06-06 10:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_auto_20180604_1436'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='TeamMember',
        ),
    ]
