# Generated by Django 2.0.4 on 2018-06-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180606_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmessage',
            name='message_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
