# Generated by Django 2.0.4 on 2018-05-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180507_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.CharField(default='', max_length=254),
        ),
    ]
