# Generated by Django 2.0.4 on 2018-05-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='project',
        ),
        migrations.AddField(
            model_name='skill',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos'),
        ),
    ]
