# Generated by Django 2.0.4 on 2018-05-13 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20180513_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSkillSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Skill')),
            ],
        ),
    ]
