# Generated by Django 2.0.4 on 2018-05-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_commitskill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requiredskills',
            name='mongodb',
        ),
        migrations.RemoveField(
            model_name='requiredskills',
            name='mysql',
        ),
        migrations.AddField(
            model_name='requiredskills',
            name='db',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
