# Generated by Django 2.0.4 on 2018-05-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20180515_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
