# Generated by Django 2.0.4 on 2018-05-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_projectstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_manager',
        ),
    ]
