# Generated by Django 2.0.4 on 2018-05-19 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_remove_project_project_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='proposed_by',
            new_name='assigned_to',
        ),
    ]
