# Generated by Django 2.0.4 on 2018-05-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20180519_0856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
