# Generated by Django 2.0.4 on 2018-05-30 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity_choice', '0001_initial'),
        ('charity_donation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity_choice.Charity')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity_donation.Donation')),
            ],
        ),
    ]
