# Generated by Django 2.0.4 on 2018-05-30 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donation', '0003_donationlineitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationlineitem',
            name='quantity',
        ),
    ]
