# Generated by Django 2.0.4 on 2018-05-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donation', '0005_donationlineitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationlineitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
