# Generated by Django 2.0.4 on 2018-06-04 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity_choice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charity',
            options={'verbose_name': 'Proposed Charity', 'verbose_name_plural': 'Proposed Charities'},
        ),
    ]
