# Generated by Django 2.0.4 on 2018-06-06 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, default='Coder', max_length=254)),
                ('personality', models.CharField(blank=True, default='', max_length=254)),
                ('image', models.ImageField(blank=True, upload_to='portraits')),
                ('my_wallet', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='undefined', max_length=254)),
            ],
            options={
                'verbose_name': 'Personality Type',
                'verbose_name_plural': 'Personality Types',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='undefined', max_length=254)),
            ],
            options={
                'verbose_name': 'Company Position',
                'verbose_name_plural': 'Company Positions',
            },
        ),
    ]
