# Generated by Django 2.0.4 on 2018-06-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180604_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='undefined', max_length=254)),
                ('answer_1', models.CharField(default='undefined', max_length=254)),
                ('answer_2', models.CharField(default='undefined', max_length=254)),
                ('answer_3', models.CharField(default='undefined', max_length=254)),
                ('answer_4', models.CharField(default='undefined', max_length=254)),
            ],
        ),
    ]
