# Generated by Django 2.0.4 on 2018-05-07 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180507_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='owner',
        ),
    ]
