# Generated by Django 2.0.4 on 2018-05-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_myprofile_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='personality',
            field=models.CharField(default='programmer', max_length=254),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='position',
            field=models.CharField(default='rookie', max_length=254),
        ),
    ]
