# Generated by Django 2.0.4 on 2018-05-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_personality_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='portraits'),
        ),
    ]
