# Generated by Django 2.0.4 on 2018-05-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180510_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='personality',
            field=models.CharField(default='geek', max_length=254),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='position',
            field=models.CharField(default='Coder', max_length=254),
        ),
    ]
