# Generated by Django 2.0.4 on 2018-05-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180517_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='actual_wallet',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
    ]
