# Generated by Django 2.0.4 on 2018-05-17 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_myprofile_actual_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myprofile',
            old_name='actual_wallet',
            new_name='my_wallet',
        ),
    ]
