# Generated by Django 2.0.4 on 2018-05-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180517_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='personality',
            field=models.CharField(blank=True, default='geek', max_length=254),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='position',
            field=models.CharField(blank=True, default='Coder', max_length=254),
        ),
    ]
